In [1]:
!pip install torch

In [1]:
import numpy as np
import csv
import shutil
import torch
import matplotlib.pyplot as plt

## Git Clone

In [3]:
#shutil.rmtree("/kaggle/working/VIPCUP2023_OLIVES_MY")      

In [2]:
%cd /kaggle/working

/kaggle/working


In [12]:
#!git clone https://github.com/KavinduKariyawasam/VIPCUP2023_OLIVES_MY.git

In [3]:
!git clone https://github.com/Pixelvision-VIP/VIPCUP2023_OLIVES_edit.git

Cloning into 'VIPCUP2023_OLIVES_edit'...
remote: Enumerating objects: 222, done.
remote: Counting objects: 100% (151/151), done.
remote: Compressing objects: 100% (126/126), done.
remote: Total 222 (delta 89), reused 42 (delta 24), pack-reused 71
Receiving objects: 100% (222/222), 1.63 MiB | 12.10 MiB/s, done.
Resolving deltas: 100% (122/122), done.


In [13]:
%cd /kaggle/working/VIPCUP2023_OLIVES_edit
!git pull
%cd ../

/kaggle/working/VIPCUP2023_OLIVES_edit
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), 52.10 KiB | 1.11 MiB/s, done.
From https://github.com/Pixelvision-VIP/VIPCUP2023_OLIVES_edit
   ecaf17f..abeedc8  main       -> origin/main
Updating ecaf17f..abeedc8
Fast-forward
 csv_dir/final_with_test.csv | 13280 ++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 13280 insertions(+)
 create mode 100644 csv_dir/final_with_test.csv
/kaggle/working


In [15]:
#!gsutil -m cp /kaggle/working/VIPCUP2023_OLIVES_edit/baseline_result.csv gs://pixelvision/pytorch9000

## Train Model

In [16]:
#output_csv_name=''#this is required for train.py edited version

In [21]:
!python /kaggle/working/VIPCUP2023_OLIVES_edit/train.py --batch_size 64 --model 'resnet101' --dataset 'OLIVES' --epochs 80 --device 'cuda:0' --train_image_path '../input/olives-vip-cup-2023' --test_image_path '../input/olives-vip-cup-2023/TEST_PHASE2/TEST_PHASE2/VIPCUPData_Phase2/DME/' --test_csv_path '/kaggle/input/olives-vip-cup-2023/TEST_PHASE2/TEST_PHASE2/Phase2_submission_template.csv' --train_csv_path '/kaggle/working/VIPCUP2023_OLIVES_edit/csv_dir/final_with_test.csv' --num_workers 2 --learning_rate 0.05 --momentum 0.9 --temp 0.07

import os

txt_file_path = '/kaggle/working/output_csv_name.txt'
try:
    with open(txt_file_path, 'r') as file:
        output_csv_name_content = file.read()
        print("Contents of the file:", output_csv_name_content)
except Exception as e:
    print("Error reading file:", e)

try:
    os.remove(txt_file_path)
    print("txt file deleted successfully.")
except Exception as e:
    print("Error deleting txt file:", e)

/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Train: [1][10/208]	
Train: [1][20/208]	
Train: [1][30/208]	
Train: [1][40/208]	
Train: [1][50/208]	
Train: [1][60/208]	
Train: [1][70/208]	
Train: [1][80/208]	
Train: [1][90/208]	
Train: [1][100/208]	
Train: [1][110/208]	
Train: [1][120/208]	
Train: [1][130/208]	
Train: [1][140/208]	
Train: [1][150/208]	
Train: [1][160/208]	
Train: [1][170/208]	
Train: [1][180/208]	
Train: [1][190/208]	
Train: [1][200/208]	
==> Saving...
csv name file created successfully.
Contents of the file: model=resnet18epochs=1batch_size=64learning_rate=0.05momentum=0.9temp=0.07
txt file deleted successfully.


In [38]:
#/kaggle/input/olives-vip-cup-2023/olives/2023 IEEE SPS Video and Image Processing (VIP) Cup - Ophthalmic Biomarker Detection/TRAIN/OLIVES/TREX_DME/TREX DME/GILA/0256GOD/V14/OD/TREXJ_000019.tif

In [23]:
print(output_csv_name_content)

model=resnet18epochs=1batch_size=64learning_rate=0.05momentum=0.9temp=0.07


In [39]:
output = np.load('/kaggle/working/output.npy')
print(output)

[[0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]


In [40]:
output=np.load('/kaggle/working/output.npy')

In [41]:
output.shape

(250, 6)

## **Generating CSV file**

In [45]:
numpy_array = output  # Your numpy array with 6 columns
csv_file_path = '/kaggle/input/olives-vip-cup-2023/TEST_PHASE2/TEST_PHASE2/Phase2_submission_template.csv'


In [46]:
csv_data = []
with open(csv_file_path, 'r') as csv_file:
    csv_reader = csv.reader(csv_file)
    for row in csv_reader:
        csv_data.append(row)


In [47]:
combined_data = []
for i in range(len(csv_data)):
    if i == 0: 
        combined_row = csv_data[i]
    else:
        csv_row = [csv_data[i][0]]
        numpy_row = numpy_array[i-1].tolist()
        combined_row = csv_row + numpy_row
    combined_data.append(combined_row)


In [48]:
output_file_path = '/kaggle/working/createdOutput'+output_csv_name_content+'.csv'  # Change this to your desired output file name
with open(output_file_path, 'w', newline='') as output_file:
    csv_writer = csv.writer(output_file)
    for row in combined_data:
        csv_writer.writerow(row)

In [49]:
#%cd /kaggle/working/

In [50]:
'''
output_zip_file_path = '/kaggle/working/createdOutput'+output_csv_name_content+'.zip'
!zip -r {output_zip_file_path} {output_file_path}

output_file_path=output_zip_file_path
'''

"\noutput_zip_file_path = '/kaggle/working/createdOutput'+output_csv_name_content+'.zip'\n!zip -r {output_zip_file_path} {output_file_path}\n\noutput_file_path=output_zip_file_path\n"

In [52]:
import zipfile

#output_csv_name_content = "your_content_name"
output_zip_file_path = '/kaggle/working/createdOutput' +'finalday_' +output_csv_name_content + '.zip'

'''
# Create the zip archive
with zipfile.ZipFile(output_zip_file_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
    zipf.write(output_file_path, os.path.basename(output_file_path))

# Update the output_file_path to point to the created zip file
output_file_path = output_zip_file_path
'''

"\n# Create the zip archive\nwith zipfile.ZipFile(output_zip_file_path, 'w', zipfile.ZIP_DEFLATED) as zipf:\n    zipf.write(output_file_path, os.path.basename(output_file_path))\n\n# Update the output_file_path to point to the created zip file\noutput_file_path = output_zip_file_path\n"

In [53]:
!gsutil -m cp {output_file_path} gs://pixelvision/pytorch9000/final

Copying file:///kaggle/working/createdOutputmodel=resnet18epochs=1batch_size=64learning_rate=0.05momentum=0.9temp=0.07.csv [Content-Type=text/csv]...
/ [1/1 files][ 10.7 KiB/ 10.7 KiB] 100% Done                                    
Operation completed over 1 objects/10.7 KiB.                                     


In [30]:
#!zip -r /kaggle/working/model.zip /kaggle/working/save/OLIVES_models/resnet18_lr_0.05_decay_0.0001_bsz_128_temp_0.07

In [31]:
torch.seed()


11945899144725594720

In [32]:
torch.manual_seed(17569191939567307870)                #previous train seed